title: Sparrow
show_downloads: true
google_analytics:
theme: jekyll-theme-hacker
collections:
  projects:
    output: true
    permalink: /:collection/:title
  writeups:
    output: true
    permalink: /:collection/:title
  hackthebox:
    output: true
    permalink: /:collection/:title
  tryhackme:
    output: true
    permalink: /:collection/:title
  post:
    output: true
    permalink: /:collection/:title

email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: /site # the subpath of your site, e.g. /blog
url: https://sparrow20.github.io # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  jekyll
exclude: [README.md]
